"""Declarative base and shared mapping helpers for all ORM models.

A consistent constraint-naming convention is configured so that Alembic
autogenerated migrations produce stable, deterministic names.
"""

import uuid
from datetime import datetime

from sqlalchemy import MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Dimension of the ArcFace face embedding stored in pgvector (Design §5.1).
EMBEDDING_DIM = 512

_NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model."""

    metadata = MetaData(naming_convention=_NAMING_CONVENTION)


class UUIDMixin:
    """Adds a non-enumerable UUID primary key."""

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """Adds a server-defaulted ``created_at`` timestamp."""

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
