"""add occupation to extracted_data

Revision ID: 29bb19e2cc18
Revises: 0001
Create Date: 2026-07-07 22:45:31.782764

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29bb19e2cc18'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'extracted_data',
        sa.Column('occupation', sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_data', 'occupation')
    # ### end Alembic commands ###
