"""initial schema

Revision ID: 8beaaa5a9d0c
Revises: 
Create Date: 2026-07-18 01:49:13.869926

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8beaaa5a9d0c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any table with a Vector column is created.
    # Autogenerate cannot know this, so it is added by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_resets',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pin_resets'))
    )
    op.create_index(op.f('ix_pin_resets_email'), 'pin_resets', ['email'], unique=False)
    op.create_index(op.f('ix_pin_resets_token_hash'), 'pin_resets', ['token_hash'], unique=True)
    op.create_table('signup_invites',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signup_invites'))
    )
    op.create_index(op.f('ix_signup_invites_email'), 'signup_invites', ['email'], unique=False)
    op.create_index(op.f('ix_signup_invites_token_hash'), 'signup_invites', ['token_hash'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('name', sa.Enum('STARTER', 'GROWTH', 'PRO', 'ENTERPRISE', name='plan_name'), nullable=False),
    sa.Column('monthly_price', sa.Integer(), nullable=True),
    sa.Column('verification_quota', sa.Integer(), nullable=False),
    sa.Column('max_branches', sa.Integer(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('api_access', sa.Boolean(), nullable=False),
    sa.Column('report_access', sa.String(length=32), nullable=False),
    sa.Column('support_level', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_subscription_plans_name'))
    )
    op.create_table('mfi_accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='mfi_status'), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('current_period_usage', sa.Integer(), nullable=False),
    sa.Column('billing_cycle_start', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_mfi_accounts_plan_id_subscription_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfi_accounts')),
    sa.UniqueConstraint('email', name=op.f('uq_mfi_accounts_email'))
    )
    op.create_table('api_keys',
    sa.Column('mfi_account_id', sa.Uuid(), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mfi_account_id'], ['mfi_accounts.id'], name=op.f('fk_api_keys_mfi_account_id_mfi_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('hashed_key', name=op.f('uq_api_keys_hashed_key'))
    )
    op.create_table('branches',
    sa.Column('mfi_account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mfi_account_id'], ['mfi_accounts.id'], name=op.f('fk_branches_mfi_account_id_mfi_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('mfi_account_id', 'name', name='uq_branches_mfi_name')
    )
    op.create_index(op.f('ix_branches_mfi_account_id'), 'branches', ['mfi_account_id'], unique=False)
    op.create_table('compliance_reports',
    sa.Column('mfi_account_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_verifications', sa.Integer(), nullable=False),
    sa.Column('status_breakdown', sa.JSON(), nullable=True),
    sa.Column('format', sa.Enum('PDF', name='report_format'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mfi_account_id'], ['mfi_accounts.id'], name=op.f('fk_compliance_reports_mfi_account_id_mfi_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_reports'))
    )
    op.create_index(op.f('ix_compliance_reports_mfi_account_id'), 'compliance_reports', ['mfi_account_id'], unique=False)
    op.create_table('users',
    sa.Column('mfi_account_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('hashed_pin', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('AGENT', 'MANAGER', 'ADMIN', name='agent_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='agent_status'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_users_branch_id_branches')),
    sa.ForeignKeyConstraint(['mfi_account_id'], ['mfi_accounts.id'], name=op.f('fk_users_mfi_account_id_mfi_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('verifications',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('mfi_account_id', sa.Uuid(), nullable=False),
    sa.Column('submission_method', sa.Enum('DASHBOARD', 'API', name='submission_method'), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'PENDING', 'REJECTED', 'APPROVED', name='verification_status'), nullable=False),
    sa.Column('reject_reason', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_verifications_agent_id_users')),
    sa.ForeignKeyConstraint(['mfi_account_id'], ['mfi_accounts.id'], name=op.f('fk_verifications_mfi_account_id_mfi_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    op.create_index(op.f('ix_verifications_client_id'), 'verifications', ['client_id'], unique=False)
    op.create_index(op.f('ix_verifications_mfi_account_id'), 'verifications', ['mfi_account_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('verification_id', sa.Uuid(), nullable=True),
    sa.Column('mfi_account_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.Enum('AGENT', 'MANAGER', 'ADMIN', 'SYSTEM', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mfi_account_id'], ['mfi_accounts.id'], name=op.f('fk_audit_logs_mfi_account_id_mfi_accounts')),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_audit_logs_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_mfi_account_id'), 'audit_logs', ['mfi_account_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_verification_id'), 'audit_logs', ['verification_id'], unique=False)
    op.create_table('duplicate_flags',
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('matched_client_id', sa.String(length=64), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.Enum('PENDING', 'CONFIRMED', 'DISMISSED', name='duplicate_resolution'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_duplicate_flags_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_flags'))
    )
    op.create_table('extracted_data',
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    # These map to app.db.types.EncryptedString / EncryptedDate in the ORM,
    # whose storage impl is LargeBinary. Rendered as the plain type here so
    # this snapshot stays self-contained — a frozen migration must not import
    # application code that may later be refactored away.
    sa.Column('full_name', sa.LargeBinary(), nullable=True),
    sa.Column('id_number', sa.LargeBinary(), nullable=True),
    sa.Column('date_of_birth', sa.LargeBinary(), nullable=True),
    sa.Column('place_of_birth', sa.LargeBinary(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('M', 'F', name='sex'), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('field_confidences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_extracted_data_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_data')),
    sa.UniqueConstraint('verification_id', name=op.f('uq_extracted_data_verification_id'))
    )
    op.create_table('face_embeddings',
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.Vector(dim=512), nullable=False),
    sa.Column('model_used', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_face_embeddings_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_embeddings'))
    )
    op.create_index(op.f('ix_face_embeddings_client_id'), 'face_embeddings', ['client_id'], unique=False)
    op.create_table('face_match_results',
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_face_match_results_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_match_results')),
    sa.UniqueConstraint('verification_id', name=op.f('uq_face_match_results_verification_id'))
    )
    op.create_table('liveness_results',
    sa.Column('verification_id', sa.Uuid(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('anti_spoof_score', sa.Float(), nullable=True),
    sa.Column('landmarks_detected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verifications.id'], name=op.f('fk_liveness_results_verification_id_verifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liveness_results')),
    sa.UniqueConstraint('verification_id', name=op.f('uq_liveness_results_verification_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liveness_results')
    op.drop_table('face_match_results')
    op.drop_index(op.f('ix_face_embeddings_client_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_table('extracted_data')
    op.drop_table('duplicate_flags')
    op.drop_index(op.f('ix_audit_logs_verification_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_mfi_account_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_verifications_mfi_account_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_client_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('users')
    op.drop_index(op.f('ix_compliance_reports_mfi_account_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_branches_mfi_account_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('api_keys')
    op.drop_table('mfi_accounts')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_signup_invites_token_hash'), table_name='signup_invites')
    op.drop_index(op.f('ix_signup_invites_email'), table_name='signup_invites')
    op.drop_table('signup_invites')
    op.drop_index(op.f('ix_pin_resets_token_hash'), table_name='pin_resets')
    op.drop_index(op.f('ix_pin_resets_email'), table_name='pin_resets')
    op.drop_table('pin_resets')
    # ### end Alembic commands ###
