"""add status_breakdown to compliance_reports

Revision ID: e08620485bc8
Revises: 29bb19e2cc18
Create Date: 2026-07-08 14:13:53.822066

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e08620485bc8'
down_revision: str | None = '29bb19e2cc18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'compliance_reports',
        sa.Column('status_breakdown', sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_reports', 'status_breakdown')
    # ### end Alembic commands ###
